### ISSUE TITLE
digest mismatch when unlocking

### ISSUE THREAD

**Issue by BrandonCopley** [TheDeveloper/warlock#16]
I am unlocking via unlock() however the unlock is not happening and I am seeing "digest mismatch" in the errors. any ideas?

**Comment by TheDeveloper** [comment]
Is it possible you are calling the unlock function multiple times?

**Comment by BrandonCopley** [comment]
It is not, because after running the function completely I can run it again
even after calling unlock.

On Monday, November 9, 2015, Geoff Wagstaff <notifications@github.com>
wrote:

> Is it possible you are calling the unlock function multiple times?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheDeveloper/warlock/issues/16#issuecomment-155054388>
> .
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by TheDeveloper** [comment]
Not sure I follow. Are you referring to the unlock function here?

**Comment by BrandonCopley** [comment]
I am calling the unlock function and receiving digest mismatch when calling
unlock so the app isn't able to unlock. I am only calling unlock once and
finding the timeout is the only thing working, the unlock function is not
functional for me due to the digest mismatch

I have warlock running other places, I just hadn't seen digest mismatch
before and am curious if there's a way to stop the mismatch or what may be
causing it.

On Monday, November 16, 2015, Geoff Wagstaff <notifications@github.com>
wrote:

> Not sure I follow. Are you referring to the unlock function here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TheDeveloper/warlock/issues/16#issuecomment-156971047>
> .
>


-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by TheDeveloper** [comment]
Thanks for the info.

What version of redis are you running? This module should be used with redis >= `v2.6.12`, and `node-redis` >= `v0.10`.
