### ISSUE TITLE
"SCRIPT is not implemented in fakeredis. Let me know if you need it."

### ISSUE THREAD

**Issue by GeoffreyPlitt** [TheDeveloper/warlock#9]
I'd like to use warlock with fake_redis for a locking pattern, and I'm getting the error above. Is SCRIPT a vital part of warlock?

See https://github.com/hdachev/fakeredis/issues/15

**Comment by TheDeveloper** [comment]
The script is used to ensure that only the original client that set the lock can release it. It's important to prevent other clients unintentionally releasing the lock with runaway requests in the case of latency / reconnections / backpressure etc.

You could replace the [script command](https://github.com/TheDeveloper/warlock/blob/master/lib/warlock.js#L55) with a redis [del](http://redis.io/commands/del), but be aware that doing so will lose this unlock safety.

**Comment by GeoffreyPlitt** [comment]
Gotcha.

Is there a way to run warlock without redis for single-process locking?

**Comment by TheDeveloper** [comment]
Not really, warlock is only intended for distributed locking across different processes.

I can see why you might want to use fake_redis for dev / testing, but with containers / homebrew / VMs etc it's getting much easier to configure test envs with deps like redis, so I normally use the real thing.
